permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883
serial:
  port: /dev/ttyUSB0
  adapter: ember
frontend:
  port: 8080
  legacy_api: false
  legacy_availability_payload: false
  log_level: error
homeassistant: true
# Example to use
